import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Roboto } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.scss";
import AppHeader from "./_components/appHeader/AppHeader";
import Footer from "./_components/footer/Footer";
import Copywrite from "./_components/copywrite/Copywrite";



const myFont = localFont({
  src:'../fonts/woff/san_francisco-webfont.woff2',
  display: 'swap'
})

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "EU Legal Assist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AppHeader/>
        <main>{children}</main>
        <footer>
        <Footer/>
        <Copywrite/>
        </footer>
        </body>
    </html>
  );
}
